---
- name: Cleanup IBM Cloud VPC VSI
  hosts: localhost
  vars:
    - tower_node: []
    - db_node: []
  collections:
   - ibm.cloudcollection
  tasks:
    - name: Fetch the variables from var file
      include_vars:
        file: vars.yml

    - name: Delete the VM's
      include_tasks: delete_vsi.yml
      loop: "{{ range(0, number_of_tower_instance + 1, 1)|list }}"

    - name: Delete SSH Key
      include_role:
        name: delete_ssh

    - name: Delete VPC Subnet
      include_role:
        name: delete_vpc_subnet

    - name: Delete Security Group
      include_role:
        name: delete_security_group

    - name: Delete VPC
      include_role:
        name: delete_vpc
