---
- name: Create IBM Cloud VPC VSI
  hosts: localhost
  vars:
    tower_node: []
    db_node: []   
  collections:
   - ibm.cloudcollection
  tasks:
    - name: Fetch the variables from var file
      include_vars:
        file: vars.yml

    - name: Configure VPC
      include_role:
        name: configure_vpc

    - name: Configure VPC Subnet
      include_role:
        name: configure_vpc_subnet

    - name: Configure SSH Key
      include_role:
        name: configure_ssh

    - name: Install the VM's
      include_tasks: create_vsi.yml
      loop: "{{ range(1, ic_instance |int + 1, 1)|list }}"

    - name: Configure Security Group Rule
      include_role:
        name: configure_security_group

    - name: Add VM's to Tower and Database group
      include_role:
        name: add_hosts
      when: install_tower | default('True') | bool

    - name: Print IBM Cloud Instance Floating IPs
      debug:
        msg: 
          - "IC instance Floating IP: "
          - "{{ tower_node + db_node }}"

- name: Check Ansible connection to new DEMO VSI
  hosts: tower database
  gather_facts: False
  tasks:
    - name: Wait for VSI to become reachable over SSH
      wait_for_connection:

- name: Check Ansible connection to new DEMO VSI
  hosts: tower[0]
  gather_facts: False
  tasks:
    - name: Fetch the variables from var file
      include_vars:
        file: vars.yml
        
    - name: Fetch the vaulted variables
      include_vars:
        file: config/credential.vault

    - name: Copy the towerperf ssh private key
      include_role:
        name: copy_key

    - name: Copy the towerperf ssh private key
      include_role:
        name: install_tower
