---
- name: Fetch SSH Keys Details
  ibm.cloudcollection.ibm_is_ssh_key_info:
    name: "{{ ibmcloud_ssh_key }}"
    region: "{{ ibmcloud_ic_region }}"
  register: ssh_key
  ignore_errors: True

- name: Cleanup SSH Key
  ibm.cloudcollection.ibm_is_ssh_key:
    name: "{{ ibmcloud_ssh_key }}"
    public_key: "{{ ssh_public_key }}"
    id: "{{ ssh_key.resource.id }}"
    state: absent
    region: "{{ ibmcloud_ic_region }}"
  register: ssh_key_delete_output
  when: ssh_key.rc == 0
  ignore_errors: True

