---
- name: Add Isolated nodes to iso group
  add_host:
    name: "{{ item }}"
    ansible_user: root
    groups: iso
    ansible_ssh_extra_args: -o StrictHostKeyChecking=no
    ansible_ssh_private_key_file: conf/towerperf_id_rsa
  loop: "{{ iso_node }}"
