---
- name: Configure VPC Subnet
  ibm.cloudcollection.ibm_is_subnet:
    name: "{{ name_prefix }}-subnet"
    state: available
    id: "{{ subnet.id | default(omit) }}"
    vpc: "{{ vpc.id }}"
     #total_ipv4_address_count: "{{ total_ipv4_address_count }}"
    ipv4_cidr_block: "{{ ipv4_cidr_block }}"
    zone: "{{ zone }}"
  register: subnet_create_output

- name: Save VPC Subnet as fact
  set_fact:
    cacheable: True
    subnet: "{{ subnet_create_output.resource }}"
