---
- debug:
    var: vpc.security_group

- name: "Configure Security Group Rule to open certain ports on the VSI when they don't exist"
  ibm.cloudcollection.ibm_is_security_group_rule:
    state: available
    group: "{{ vpc.default_security_group }}"
    region: "{{ ibmcloud_ic_region }}"
    direction: inbound
    remote: 0.0.0.0/0
    tcp:
      - port_max: "{{ item }}"
        port_min: "{{ item }}"
  loop: "{{ list_of_ports }}"
  when: vpc.security_group[0].rules|length < list_of_ports|length

- name: "Configure Security Group Rule to open icmp on the VSI"
  ibm.cloudcollection.ibm_is_security_group_rule:
    state: available
    group: "{{ vpc.default_security_group }}"
    region: "{{ ibmcloud_ic_region }}"
    direction: inbound
    remote: 0.0.0.0/0
    icmp:
      - type: 8
  when: vpc.security_group[0].rules|length < list_of_ports|length
