---
- name: Add nodes to group
  add_host:
    name: "{{ item }}"
    ansible_user: root
    groups: "{{ group_name }}"
    ansible_ssh_extra_args: -o StrictHostKeyChecking=no
    ansible_ssh_private_key_file: conf/towerperf_id_rsa
  loop: "{{ host_ips }}"
